version: '2.4'

services:
  ps3netsrv:
    container_name: ps3netsrv
    build:
      context: .
    restart: unless-stopped
    volumes:
      - /mnt/DeepStorage/Data/isos/PS3:/games
    ports:
      - 38008:38008/tcp
